### ISSUE TITLE
ROS buildfarm release

### ISSUE THREAD

**Issue by Timple** [hbanzhaf/steering_functions#11]
Thank you for this wonderful package. 

Would you be interested in releasing this package so people can 
`apt install ros-noetic-steering-functions`?

[It's not hard](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) but will take you an hour or so the very first time. If you like I can assist with that (I do the same for [ublox_gps](https://github.com/KumarRobotics/ublox)).
Or I can do the complete release if you like.

Thanks for considering.

**Comment by Timple** [comment]
I took the liberty of already checking the prerelease tests using this ugly one-liner:

```
cd $(mktemp -d) && generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   noetic default ubuntu focal amd64   --custom-repo     steering_functions__custom-1:git:https://github.com/hbanzhaf/steering_functions.git:master   --level 1   --output-dir ./ && ./prerelease.sh 
```

It took a while but succeeded succesfully!

**Comment by Timple** [comment]
Would you like me to release it? I only need you to bump the version in the `package.xml` and create a git-tag with the version number.

(I cannot open a PR for that since tags cannot be PRed)

**Comment by hbanzhaf** [comment]
Sounds good. Let's do it this way.

**Comment by Timple** [comment]
Cool!

Go ahead with the commit and tag. I'll pick it up from there

**Comment by hbanzhaf** [comment]
I now created the tag 0.0 which corresponds to the version in the package.xml. Let me know if anything else is needed.

**Comment by Timple** [comment]
I was happy with the 1.0.0 before. Just needed the tag.

A ROS package [must ](http://wiki.ros.org/catkin/package.xml#Required_Tags)have three digits though. So if you can make it either 0.0.0 or 1.0.0 with corresponding tag that would be great!

I'll try to make the release before july.

**Comment by hbanzhaf** [comment]
I made the required changes. Let me know if anything else is missing.

**Comment by Timple** [comment]
As per comment here: https://github.com/ros/rosdistro/pull/30052#issuecomment-871526795

Would you mind bumping the version?

**Comment by Timple** [comment]
Forwarding a subtle [ping](https://github.com/ros/rosdistro/pull/30052#issuecomment-874125863) :slightly_smiling_face:

**Comment by hbanzhaf** [comment]
Version number and tag have now been adjusted accordingly.
