### ISSUE TITLE
Proper namespace

### ISSUE THREAD

**Issue by vebjornjr** [hbanzhaf/steering_functions#14]
Hey!

First of all, thank you for providing this library. It has been very helpful.

I want to suggest a small improvement of the library.
At the moment, the library doesn't follow common guidelines for namespaces in C++.
All the code in the library should be in a namespace.
The code in steering_functions.hpp are in the namespace "steer", while code such as CC_Dubins_State_Space are not in any namspace.
I also suggest that the namespace should be called "steering" to match with the repository name here on Github.
Also, "using namespace [...]" should not be used in header files as it causes problems when including the header files.
E.g. your class Path has a very generic name which is very likely to crash with other names for users of this library.

I can make a pull request with the required changes, I just wanted to coordinate with you beforehand.
If you don't agree and don't want to merge the changes, then I won't waste my time creating a pull request.

Here are some resources on the topic:

[cppbestpractices](https://github.com/cpp-best-practices/cppbestpractices/blob/ad81298a259a45e74dacb1a74f8fd5056700b78a/03-Style.md#never-use-using-namespace-in-a-header-file)

[C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-using-directive)

[Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Namespaces)

**Comment by hbanzhaf** [comment]
Sure, sounds good. Please follow the contribution guidelines when submitting a PR.

**Comment by Timple** [comment]
As a user of this wonderfull library, I'm good with the changes proposed.

I would expect and entry in the changelog and a version bump in the package.xml though.
