### ISSUE TITLE
Is it possible to use the Reed-Shepp with continuous curvature at cusps?

### ISSUE THREAD

**Issue by jcsantamaria** [hbanzhaf/steering_functions#20]
Hi Holger,
Currently, the HC_Reeds_Shepp_State_Space class is able to compute trajectories from a start state to a goal state with forward/reverse segments.  And at the cusp states, it is possible to have discontinuous curvatures: for example, arriving at cusp curv is max_curv, but leaving at cusp curv is -max_curv.  This assumes that the vehicle is able to go from max_steer to -max_steer while stationary.

Is there a simple way to enforce the curv to be continuous at cusp states?   This is for the use case of, say, a heavy articulated steering vehicle that cannot change steering while stationary.

**Comment by jcsantamaria** [comment]
But there is no generic CC_Reeds_Shepp_State_Space class (like the generic CC_Dubins_State_Space), is it?
Are you referring to CC00_Reeds_Shepp_State_Space class?   This one is only for start/goal states having 0 curvature, right?

**Comment by hbanzhaf** [comment]
That's right. CC_Reeds_Shepp_State_Space would still need to be implemented. This should be simple with the insights from the other state spaces and this publication: https://publikationen.bibliothek.kit.edu/1000104500
