### ISSUE TITLE
CC0pm_Dubins incorrect end curvature

### ISSUE THREAD

**Issue by CharlotteAx** [hbanzhaf/steering_functions#21]
The CC0pm_Dubins steering function does not seem to use the provided curvature of the goal state as curvature goal (it doesn't seem to use this value at all). Instead, the curvature at the end of the path is equal to the maximum curvature given to the function. I would expect that the maximum curvature is used to create the path, but that the end state of the path should include the provided curvature of the goal state, not the maximum curvature.

I think the other steering functions with 'pm' have the same issue.

**Comment by hbanzhaf** [comment]
CC0pm means that you are enforcing zero curvature at the start and +/- curvature at the end (for the latter, you let the algorithm decide).
If you want to enforce a given curvature at the start and end, you would need to use the CC_Dubins state space.
