### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Timple** [hbanzhaf/steering_functions#25]
Hi!

Would you mind making a new release?

For example `0.3.1`. For ROS releases it's also important that a git tag with the corresponding version exists.

Thank you!

**Comment by Timple** [comment]
Or only add a git tag `0.3.0` corresponding to the current package.xml would also suffice :+1:

**Comment by hbanzhaf** [comment]
@Timple New tag added. Hope this helps.

**Comment by Timple** [comment]
Thanks!
