### ISSUE TITLE
Curvature discontinuities observed at start and goal. Is it expected?

### ISSUE THREAD

**Issue by Shantnu12345** [hbanzhaf/steering_functions#3]
Hi respected developers,

First of all thank you for sharing the code. I am using it to plan a smooth path from a start to goal, however I am observing curvature discontinuities at the start and goal. For example, when planning path using HC-RS (Hybrid-curvature reeds-shepp)  from a start point (0, -8, PI, kappa, 0) to a goal point (0, 0, 0, kappa, 0), the curvature directly jumps from -maxKappa to maxKappa at the start and then from -maxKappa to maxKappa at the goal. The kappa that I am taking is 0.348174 ( which is tand(40)/wheelbase ) and I am keeping sigma = kappa. 

Is this jump expected or am I using the model wrong? The following shows the generated path as x, y, theta, kappa. It can be observed that the there is a jump from 0.348174 to -0.34817 at start and then from -0.34817 to 0.348174 at the goal.

 x            | y              | theta      | kappa
 0.00000 | - 8.00000 | 3.14159 | 0.348174
 0.00000 | -8.00000 | 3.14159 | -0.34817
-0.09998 | -7.99826 | 3.10678 | -0.34817
-0.19984 | -7.99304 | 3.07196 | -0.34817
-0.29946 | -7.98435 | 3.03714 | -0.34817
-0.39871 | -7.97219 | 3.00232 | -0.34817
-0.49748 | -7.95659 | 2.96751 | -0.34817
-0.59565 | -7.93756 | 2.93269 | -0.34817
-0.69309 | -7.91512 | 2.89787 | -0.34817
-0.7897 | -7.8893 | 2.86305 | -0.34817
-0.88534 | -7.86014 | 2.82824 | -0.34817
-0.97992 | -7.82766 | 2.79342 | -0.34817
-1.0733 | -7.79192 | 2.7586 | -0.34817
-1.16539 | -7.75294 | 2.72378 | -0.34817
-1.25606 | -7.71078 | 2.68897 | -0.34817
-1.34521 | -7.66549 | 2.65415 | -0.34817
-1.43273 | -7.61713 | 2.61933 | -0.34817
-1.51852 | -7.56574 | 2.58451 | -0.34817
-1.60246 | -7.51141 | 2.5497 | -0.34817
-1.68446 | -7.45418 | 2.51488 | -0.34817
-1.76442 | -7.39413 | 2.48006 | -0.34817
-1.84224 | -7.33134 | 2.44524 | -0.34817
-1.91783 | -7.26587 | 2.41043 | -0.34817
-1.99109 | -7.19782 | 2.37561 | -0.34817
-2.06194 | -7.12725 | 2.34079 | -0.34817
-2.13029 | -7.05426 | 2.30597 | -0.34817
-2.19606 | -6.97894 | 2.27116 | -0.34817
-2.25916 | -6.90137 | 2.23634 | -0.34817
-2.31953 | -6.82166 | 2.20152 | -0.34817
-2.37708 | -6.73989 | 2.16671 | -0.34817
-2.43176 | -6.65616 | 2.13189 | -0.34817
-2.48348 | -6.57059 | 2.09707 | -0.34817
-2.5322 | -6.48326 | 2.06225 | -0.34817
-2.57785 | -6.39429 | 2.02744 | -0.34817
-2.62037 | -6.30379 | 1.99262 | -0.34817
-2.65971 | -6.21186 | 1.9578 | -0.34817
-2.69584 | -6.11862 | 1.92298 | -0.34817
-2.72869 | -6.02417 | 1.88817 | -0.34817
-2.75824 | -5.92864 | 1.85335 | -0.34817
-2.78444 | -5.83214 | 1.81853 | -0.34817
-2.80727 | -5.73479 | 1.78371 | -0.34817
-2.8267 | -5.6367 | 1.7489 | -0.34817
-2.82871 | -5.62535 | 1.74488 | -0.34817
-2.84437 | -5.52659 | 1.71181 | -0.31336
-2.85693 | -5.42739 | 1.68221 | -0.27854
-2.86672 | -5.32787 | 1.6561 | -0.24372
-2.87409 | -5.22814 | 1.63347 | -0.2089
-2.87937 | -5.12828 | 1.61432 | -0.17409
-2.8829 | -5.02835 | 1.59865 | -0.13927
-2.88505 | -4.92837 | 1.58646 | -0.10445
-2.88615 | -4.82838 | 1.57776 | -0.06963
-2.88656 | -4.72838 | 1.57254 | -0.03482
-2.88662 | -4.62838 | 1.5708 | 1.39E-17
-2.88662 | -4.52838 | 1.5708 | 1.39E-17
-2.88662 | -4.42838 | 1.5708 | 1.39E-17
-2.88662 | -4.32838 | 1.5708 | 1.39E-17
-2.88662 | -4.22838 | 1.5708 | 1.39E-17
-2.88662 | -4.12838 | 1.5708 | 1.39E-17
-2.88662 | -4.02838 | 1.5708 | 1.39E-17
-2.88662 | -3.92838 | 1.5708 | 1.39E-17
-2.88662 | -3.82838 | 1.5708 | 1.39E-17
-2.88662 | -3.72838 | 1.5708 | 1.39E-17
-2.88662 | -3.62838 | 1.5708 | 1.39E-17
-2.88662 | -3.52838 | 1.5708 | 1.39E-17
-2.88662 | -3.42838 | 1.5708 | 1.39E-17
-2.88662 | -3.37162 | 1.5708 | 1.39E-17
-2.88656 | -3.27162 | 1.56906 | -0.03482
-2.88615 | -3.17162 | 1.56383 | -0.06963
-2.88505 | -3.07163 | 1.55513 | -0.10445
-2.8829 | -2.97165 | 1.54294 | -0.13927
-2.87937 | -2.87172 | 1.52727 | -0.17409
-2.87409 | -2.77186 | 1.50812 | -0.2089
-2.86672 | -2.67213 | 1.48549 | -0.24372
-2.85693 | -2.57261 | 1.45938 | -0.27854
-2.84437 | -2.47341 | 1.42979 | -0.31336
-2.82871 | -2.37465 | 1.39671 | -0.34817
-2.80968 | -2.27648 | 1.36189 | -0.34817
-2.78725 | -2.17904 | 1.32707 | -0.34817
-2.76143 | -2.08243 | 1.29226 | -0.34817
-2.73227 | -1.98678 | 1.25744 | -0.34817
-2.69979 | -1.89221 | 1.22262 | -0.34817
-2.66404 | -1.79882 | 1.1878 | -0.34817
-2.62507 | -1.70674 | 1.15299 | -0.34817
-2.58291 | -1.61606 | 1.11817 | -0.34817
-2.53762 | -1.52691 | 1.08335 | -0.34817
-2.48925 | -1.43939 | 1.04854 | -0.34817
-2.43787 | -1.35361 | 1.01372 | -0.34817
-2.38353 | -1.26967 | 0.9789 | -0.34817
-2.32631 | -1.18766 | 0.944083 | -0.34817
-2.26626 | -1.10771 | 0.909266 | -0.34817
-2.20347 | -1.02989 | 0.874448 | -0.34817
-2.138 | -0.9543 | 0.839631 | -0.34817
-2.06994 | -0.88104 | 0.804813 | -0.34817
-1.99938 | -0.81019 | 0.769996 | -0.34817
-1.92639 | -0.74184 | 0.735178 | -0.34817
-1.85107 | -0.67607 | 0.700361 | -0.34817
-1.7735 | -0.61297 | 0.665544 | -0.34817
-1.69378 | -0.5526 | 0.630726 | -0.34817
-1.61201 | -0.49504 | 0.595909 | -0.34817
-1.52829 | -0.44037 | 0.561091 | -0.34817
-1.44271 | -0.38864 | 0.526274 | -0.34817
-1.35539 | -0.33993 | 0.491457 | -0.34817
-1.26642 | -0.29428 | 0.456639 | -0.34817
-1.17592 | -0.25176 | 0.421822 | -0.34817
-1.08399 | -0.21241 | 0.387004 | -0.34817
-0.99074 | -0.17629 | 0.352187 | -0.34817
-0.8963 | -0.14344 | 0.31737 | -0.34817
-0.80077 | -0.11389 | 0.282552 | -0.34817
-0.70427 | -0.08768 | 0.247735 | -0.34817
-0.60692 | -0.06486 | 0.212917 | -0.34817
-0.50883 | -0.04543 | 0.1781 | -0.34817
-0.41012 | -0.02943 | 0.143282 | -0.34817
-0.31092 | -0.01688 | 0.108465 | -0.34817
-0.21133 | -0.00779 | 0.073648 | -0.34817
-0.1115 | -0.00217 | 0.03883 | -0.34817
-0.01153 | -2.31E-05 | 0.004013 | -0.34817
-3.70E-14 | -3.28E-15 | 6.73E-15 | -0.34817
-3.70E-14 | -3.28E-15 | 6.73E-15 | 0.348174

Your help would be extremely useful for my research.

Best regards,
Shantnu

**Comment by hbanzhaf** [comment]
Hi Shantnu,

I briefly looked into your problem. So if I understand you correctly, you want to connect:
- a start state with [0.0, -8.0, pi, +kappa_max]
- and a goal state with [0.0, 0.0, 0.0, +kappa_max]

using the _HC_Reeds_Shepp_State_Space_ (kappa_max = 0.348174 m⁻¹ and sigma_max = 0.348174 m⁻²).

In this case, the _HC_Reeds_Shepp_State_Space_ directly applies the _HCpmpm_Reeds_Shepp_State_Space_, but constrains its solution to the given start and goal curvature. The result is a steering procedure of the family TcTSTcT (more precisely TcTeSTcT), where the first and the second turn is described by a RS turn. Looking into the corresponding controls shows that the initial  and final input requires the vehicle to move forwards by 0 m with +kappa_max (sigma = 0 m⁻²). So your question boils down to whether RS turns with zero length are allowed at both ends of the path. This is the case in the current implementation, but could be adjusted by dismissing candidate paths with the described behavior.

Best regards,
Holger

**Comment by Shantnu12345** [comment]
Thank you Holger for your response. Your explanation makes sense. It would be extremely helpful if you could direct me to the specific part of the code that needs to be modified to achieve the desired behavior (rule out paths that turn with zero length).

**Comment by hbanzhaf** [comment]
Without having analyzed the consequences with respect to completeness, symmetry, or the topological property, you could realize this by:
1) Identify all families of the _HCpmpm_Reeds_Shepp_State_Space_ that have a RS turn at the start and/or at the goal (e.g. TcTT has only one RS turn at the start and TcTSTcT has one at both ends of the path).
2) After the path is computed, check if the length of the RS turn(s) is smaller than some epsilon value. If so, neglect that path. For the familiy TcTSTcT, for instance, you could add your modifications here:
https://github.com/hbanzhaf/steering_functions/blob/560f13af31de52fe8ef3ae89912658336cc26aff/src/hc_cc_state_space/hcpmpm_reeds_shepp_state_space.cpp#L1653-L1659

In this case, you can retrieve the length of the two RS turns by:
`cstart[hc_cc_rs::TcTSTcT]->rs_turn_length(*qi1[hc_cc_rs::TcTSTcT])`
`cend[hc_cc_rs::TcTSTcT]->rs_turn_length(*qi4[hc_cc_rs::TcTSTcT])`
