### ISSUE TITLE
Wrong path in a u-turn case

### ISSUE THREAD

**Issue by jcsantamaria** [hbanzhaf/steering_functions#4]
Hi Maintainers,  (thank you for this repository!)

I found an issue when generating a simple u-turn with cc_dubins.  The code is:

`

	// construct cc dubins engine
	CC_Dubins_State_Space cc_dubins_forwards_ss(0.699249625, 0.0272707697, 1.0, true);

	// initial start
	steer::State start(0.0, 3.0480000972747803, 3.1415927410125732, 0.0);
	steer::State goal(0.0, 0.0, 0.0, 0.0);

	std::vector<steer::State> path = cc_dubins_forwards_ss.get_path(start, goal);
`

The path generated is like this:
![image](https://user-images.githubusercontent.com/3914378/56423594-d294a580-627a-11e9-9f59-39fda156dc9a.png)

I was able to fix this trajectory by making this change on line 118 of cc00_dubins_state_space.cpp (function TeST_exists()):

`    return (distance >= 2 * c1.radius);// *c1.sin_mu);
`

Here it is the resulting path when commenting out the sin_mu factor:
![image](https://user-images.githubusercontent.com/3914378/56423745-931a8900-627b-11e9-88ca-f2ac4da5647a.png)

I think TeST is related to the Dubins Turn-Straight-Turn, but I don't quite understand the difference between TiST and TeST.  By the way, TiST does not have the sin_mu factor.

I hope this helps.

**Comment by hbanzhaf** [comment]
Problem should be resolved with f3564e2ad53259485e7eebe91d674d211783be61 (also see https://github.com/hbanzhaf/steering_functions/issues/5#issuecomment-509006090):

![u_turn](https://user-images.githubusercontent.com/9086412/60770338-47d58100-a0da-11e9-8c99-6eb156afddd6.png)

**Comment by henrychoi** [comment]
Both the 2017 and 2018 papers discuss collision checking, but I cannot find obstacles in this code base.  Can you please point me toward how the external obstacles are handled?
