### ISSUE TITLE
Code of integrated with RRT*

### ISSUE THREAD

**Issue by peterWon** [hbanzhaf/steering_functions#7]
Hi, hbanzhaf, thanks a lot for your great work, I wonder that is there any code of reeds-sheep with RRT* you have mentioned in the readme's youtube video. thanks!

**Comment by hbanzhaf** [comment]
Hello Peter,
Thanks a lot for your interest. You could use the [OMPL](http://ompl.kavrakilab.org/2012/03/18/geometric-planning-for-car-like-vehicles.html) to combine RRT* with the Reeds-Shepp steering function.
Best,
Holger
